# Generated by Django 3.2.9 on 2021-11-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
